// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoYC2Ch5zz0KLhDkWrdSsrzT3RuA1Oas',
    appId: '1:1043981001459:web:cd9db7c206f8deed2acd86',
    messagingSenderId: '1043981001459',
    projectId: 'futterauthen',
    authDomain: 'futterauthen.firebaseapp.com',
    storageBucket: 'futterauthen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxbRB1EiQh16EUN3AY2-oIME2c2CnVOkI',
    appId: '1:1043981001459:android:5009658511b4cfd32acd86',
    messagingSenderId: '1043981001459',
    projectId: 'futterauthen',
    storageBucket: 'futterauthen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82PmLQsdckuxeEbMcAm-xUYmfOeQz0Yk',
    appId: '1:1043981001459:ios:5dd33285f8488b4b2acd86',
    messagingSenderId: '1043981001459',
    projectId: 'futterauthen',
    storageBucket: 'futterauthen.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD82PmLQsdckuxeEbMcAm-xUYmfOeQz0Yk',
    appId: '1:1043981001459:ios:303bccfd31278a6b2acd86',
    messagingSenderId: '1043981001459',
    projectId: 'futterauthen',
    storageBucket: 'futterauthen.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
